theme: jekyll-theme-cayman
title: Credit Card Fraud Detection and Model Evaluation
description: Eugene Agronin, Ph.D. | eagronin@gmail.com 
github:
  home_url: https://eagronin.github.io/portfolio/
  tar_url: https://www.linkedin.com/in/eagronin
